[[words]]
phrase = "主格"
shortcut = "しゅかく"

[[words]]
phrase = "属格"
shortcut = "ぞっかく"

[[words]]
phrase = "与格"
shortcut = "よかく"

[[words]]
phrase = "対格"
shortcut = "たいかく"

[[words]]
phrase = "奪格"
shortcut = "だっかく"

[[words]]
phrase = "呼格"
shortcut = "こかく"

[[words]]
phrase = "地格"
shortcut = "ちかく"
