model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
# https://x.com/kenn/status/2008459522483073042
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Glass.aiff"]
personality = "pragmatic"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
